#!/bin/sh

# shellcheck disable=SC1090
. "${DOTFILES:-.}/shell/.shell/lib/utils.sh"

# WAITING emacs 27 won't need xterm-24 bit anymore
tic -x -o ~/.terminfo "${DOTFILES:=.}/emacs/_xterm-24bits.terminfo"
tic -x -o ~/.terminfo "$DOTFILES/alacritty/_alacritty.terminfo"

theme_template "$XDG_CONFIG_HOME/alacritty/alacritty.yml.m4"
