#!/usr/bin/env sh

set -e

: ${dotfiles:="$HOME/.dotfiles"}

if ! [ -d "${HOME}/.local/src/bork" ]; then
	mkdir -p ~/.local/{src,bin}
	git clone https://github.com/mattly/bork ~/.local/src/bork
	ln -sf ~/.local/src/bork/bin/bork ~/.local/bin/bork
	ln -sf ~/.local/src/bork/bin/bork-compile ~/.local/bin/bork-compile
fi

source ./env/profile

if ! [ -d "${dotfiles}" ]; then
	git clone https://github.com/bricewge/dotfiles $dotfiles
fi

# I want to use ssh keys to authenticate with github, not credentials
if [[ $USER == "bricewge" ]] || [[ $USER == "bwaegene" ]]; then
	git -C $dotfiles remote set-url origin git@github.com:bricewge/dotfiles.git
fi
