#+TITLE: dotfiles
Brice Waegeneire's dotfiles for GNU/Linux managed with [[https://saltstack.com/][SaltStack]].

* Using thoses dotfiles
1. Install =saltstack= from your package manager.
2. =$ git clone https://github.com/bricewge/dotfiles=
3. =$ ./init.sh=

* Integrate it in your salt master
If you find this dotfiles usefull you can integrate a part or all of
it to your usual saltstack workflow with a master.

You'll need to modify your salt master config by adding the path where
you clone this repo –for example =/home/fordprefect/dotfiles=- to =file_roots=.
#+BEGIN_SRC yaml /etc/salt/master
  file_roots:
    base:
      - /srv/salt
      - /home/fordprefect/dotfiles
#+END_SRC

Now include the parts you want to your =top.sls=. Maybe for your
=bar= machine you only need to configure =emacs=, =termite= and =zsh=.
#+BEGIN_SRC yaml /srv/salt/top.sls
  base:
    '*':
      - foo
    'bar':
      - emacs
      - termite
      - zsh
#+END_SRC

Then you need to set a pillar with the username and paths which are
noramally set by the =init.sh= script.
#+BEGIN_SRC yaml /srv/pillar/dotfiles.sls
  dotfiles:
    user: fordprefect
    home: /home/fordprefect
    fileroot: /home/fordprefect/dotfiles
#+END_SRC

Finally you can apply the states you choosed with an usual
=state.highstate= along side yours.
#+BEGIN_SRC sh
 $ sudo salt '*' state.highstate
#+END_SRC

* License
All of this repository is under [[https://creativecommons.org/publicdomain/zero/1.0/][CC0 1.0]] license except the =wallpaper= subdirectory.
