#! /bin/sh
#
# Example panel for LemonBoy's bar

logo="\\f7\\ab  \\ac ~/.config/bspwm/panel/scripts/spawn_dmenu \\ae"
while read -r line ; do
	case $line in
	S*)
		sys_infos="\\r${line#?}\\fr"
	;;
	T*)
		title="\\br\\f7 ${line#?} \\f9"
	;;
	W*)
		wm_infos=""
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
			[OFU]*)
				# active desktop
				wm_infos="$wm_infos\\ab\\f9  \\fr\\ac bspc desktop -f ${name}\\ae"
			;;
			o*)
				# inactive but occupied desktop
				wm_infos="$wm_infos\\ab\\f8  \\fr\\ac bspc desktop -f ${name}\\ae"
			;;
			f*)
				# inactive desktop echo -e '\uE098'
				wm_infos="$wm_infos\\ab\\f8  \\fr\\ac bspc desktop -f ${name}\\ae"
			;;
			u*)
				# urgent desktop
				wm_infos="$wm_infos\\ab\\f3\\fr\\ac bspc desktop -f ${name}\\ae"
			;;
			L*)
				# # layout
				# case $name in
				# t*)
				# 	layout=""
				# ;;
				# m*)
				# 	layout=""
				# ;;
				# esac
				# wm_infos="$wm_infos \\ab\\f7$layout\\ac bspc desktop -l next\\ae"
			;;
			esac
			shift
		done
	;;
	esac
	#printf "%s\n" "$logo $wm_infos $title $sys_infos"
	# bring it all together
	left="$logo $title"
	middle="$wm_infos"
	right="$sys_infos"
	# and print to bar
	#echo "$left\\c$middle\\r$right"
	printf "%s\n" "$left\\c$middle\\r$right"
done
