#!/usr/bin/env sh

# * bspwm config
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d TV
bspc desktop -f 3

# TEST
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
# TEST

bspc config top_padding 30

export BSPWM_GAP=16
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# ** borders
bspc config border_width 2
bspc config normal_border_color "#586e75"
bspc config active_border_color "#268bd2"
bspc config focused_border_color "#93a1a1"
bspc config presel_feedback_color "#b58900"

# ** windows rules
bspc rule -a Pinentry state=floating sticky=on
bspc rule -a Emacs state=tiled # needed because of issue #551 in bspwm
bspc rule -a Emacs:capture state=floating sticky=on
bspc rule -a Gimp state=floating

# * other stuff to start
MONITOR=eDP1 polybar --reload example &
MONITOR=HDMI1 polybar --reload example &

# Enable hotkeys
# SXHKD_SHELL=/bin/sh sxhkd &
SXHKD_SHELL=/bin/sh
sxhkd_fifo=${HOME}/tmp/sxhkd.fifo
mkfifo "${sxhkd_fifo}" ; sxhkd -s "${sxhkd_fifo}" &

# To get rofi-pass working
setxkbmap fr mac
# From ~/.xinitrc
xrdb ~/.Xresources
# Load terminus font for bar
#xset +fp /usr/share/fonts/local
#xset fp rehash

# Set a wallpaper
if [[ -x "${HOME}"/.fehbg ]]; then
    "${HOME}"/.fehbg &
else
    feh --bg-fill ~/image/fp0Jtgr.jpg &
fi
# Hide the cursor when not used
xbanish -i Mod4 &
# Use a basic cursor
xsetroot -cursor_name left_ptr &
# Fancy things *BUT* with too much bugs
# compton &
udiskie --notify &
# disable DPMS
xset s off -dpms
