#!/usr/bin/env sh

source "${HOME}/.xprofile"
source "${HOME}/.profile"

# * Early setup
# Setup monitors
autorandr --change --force
# Set a wallpaper
if [[ -x "${HOME}"/.fehbg ]]; then
    "${HOME}"/.fehbg &
else
    feh --bg-fill ~/picture/wallpaper/schicka-307-unsplash.jpg &
fi
# Set a nice cursor
xsetroot -cursor_name left_ptr

# Enable hotkeys
# SXHKD_SHELL=/bin/sh sxhkd &
SXHKD_SHELL=/run/current-system/sw/bin/sh sxhkd -t 2 &
sxhkd_fifo=/tmp/sxhkd-${USER}.fifo
# SEGV
#mkfifo "${sxhkd_fifo}"
#sxhkd -s "${sxhkd_fifo}" &
#sleep 5 && killall sxhkd
#sxhkd &

# * bspwm config
bspc monitor LVDS1 -d I II III IV V
# bspc monitor HDMI1 -d 1 2 3 4 5
bspc desktop -f III

# TEST
bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
# TEST

bspc config top_padding 30

export BSPWM_GAP=16
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# ** borders
bspc config border_width 2
bspc config normal_border_color "#586e75"
bspc config active_border_color "#268bd2"
bspc config focused_border_color "#93a1a1"
bspc config presel_feedback_color "#b58900"

# ** windows rules
bspc rule -a Pinentry state=floating sticky=on
bspc rule -a Emacs state=tiled # needed because of issue bspwm/551
bspc rule -a Emacs:capture state=floating sticky=on
bspc rule -a Gimp state=floating
bspc rule -a .zathura-wrapped_ state=tiled
bspc rule -a Nightly state=tiled
bspc rule -a Nightly:Dialog state=floating

# * other stuff to start
MONITOR=LVDS1 polybar --reload example &
# MONITOR=eDP1 polybar --reload example &
# MONITOR=HDMI1 polybar --reload example &

# polybar-auto.sh &

# cd ~/tmp/umonitor && ./usr/bin/umonitor --listen && cd -
# To get rofi-pass working
# setxkbmap fr mac
# From ~/.xinitrc
xrdb ~/.Xresources
# Load terminus font for bar
#xset +fp /usr/share/fonts/local
#xset fp rehash

# Hide the cursor when not used
xbanish -i Mod4 &
# Fancy things *BUT* with too much bugs
# compton &
udiskie --notify &
bspc rule -a TermiteDropdown sticky=on floating=on
dropdown.sh &
# disable DPMS
xset s off -dpms
