#!/bin/sh

# shellcheck disable=SC1090
. "${DOTFILES:-.}/shell/.shell/lib/utils.sh"

# Disable chromium decorations
chromium_config=$HOME/.config/chromium/Default/Preferences
if [ -e "$chromium_config" ]; then
    jq < "$chromium_config" .browser.custom_chrome_frame=false \
        > /tmp/tmpfile && mv --force /tmp/tmpfile "$chromium_config"
fi

theme_template "$XDG_CONFIG_HOME/bspwm/bspwmrc.m4"
theme_template "$XDG_CONFIG_HOME/polybar/config.m4"
