#!/bin/sh

set -e

if [ "/home/bricewge/.config/termite/config" -ef \
     "/home/bricewge/.config/termite/dark" ]; then
    ln -sf /home/bricewge/.config/termite/light /home/bricewge/.config/termite/config
    emacsclient --eval "(load-theme 'solarized-light)"
elif [ "/home/bricewge/.config/termite/config" -ef \
     "/home/bricewge/.config/termite/light" ]; then
    ln -sf /home/bricewge/.config/termite/dark /home/bricewge/.config/termite/config
    emacsclient --eval "(load-theme 'solarized-dark)"
fi

killall -s USR1 termite
