#!/usr/bin/env sh
#
# Script executed when bspwm is started.

# shellcheck disable=SC1090
. "$HOME/.xprofile"
. "$HOME/.profile"

PATH=$XDG_CONFIG_HOME/bspwm:$PATH

# * Early setup
# Setup monitors
autorandr --change --force
# Set a wallpaper
if [ -x "$XDG_CONFIG_HOME/setroot/.setroot-restore" ]; then
    setroot --restore &
else
    setroot --store --blank-color '#002b36' \
        --on 0 --blur 10 -z "$DOTFILES/_wallpaper/schicka-307-unsplash.jpg" \
        --on 1 --blur 10 z "$DOTFILES/_wallpaper/schicka-307-unsplash.jpg" &

fi
# Set a nice cursor
xsetroot -cursor_name left_ptr

# ** sxhkd
SXHKD_FIFO=${HOME}/.sxhkd.fifo
[ -e "$SXHKD_FIFO" ] && rm "$SXHKD_FIFO"
mkfifo "$SXHKD_FIFO"
sxhkd -s "$SXHKD_FIFO" -t 2 &
sxhkd-listener.sh &

# * bspwm config
bspc monitor LVDS1 -d 1

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config top_padding \
    "$(awk '$1~/^height$/ {print $3}' < "$XDG_CONFIG_HOME/polybar/config")"

export BSPWM_GAP=16
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# ** borders
bspc config border_width 2
bspc config normal_border_color "#586e75"
bspc config active_border_color "#268bd2"
bspc config focused_border_color "#93a1a1"
bspc config presel_feedback_color "#002b36"

# ** windows rules
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external-rules"

# TODO move them to external rules
bspc rule -a 'Nightly:*' state=floating # Firefox
bspc rule -a Nightly:Navigator state=tiled

# * other stuff to start
scu restart redshift &
# run polybars on all monitors
polybars.sh

xrdb ~/.Xresources

# Hide the cursor when not used
xbanish -i Mod4 &
# Fancy things *BUT* with too much bugs
# compton &
udiskie --notify &
# disable DPMS
xset s off -dpms

# blur wallpaper of occupied displays
wallpaper-blur &

# Local Variables:
# eval: (rainbow-mode 1)
# End:
