#!/usr/bin/env zsh
#
# bspwm external rules

set -e

# * manual tiling
rules=()
receptacle=$(bspc query -N -n 'any.leaf.!window' || true)
preselection=$(bspc query -N -n 'newest.!automatic' || true)

if [ -n "$receptacle" ]; then
    target="$receptacle"
    attention="off"
elif [ -n "$preselection" ]; then
    target="$preselacle"
fi

rules+=( "node = ${target:-focused}" )
rules+=( "follow = ${attention:-on}" )
echo "$rules"

# * windows rules
wid=$1
class=$2
instance=$3
intermediate_consequences=$4
name=$(xwininfo -id "$wid" | sed ' /^xwininfo/!d ; s,.*"\(.*\)".*,\1,')
rules=()

case $class in
    [Pp]inentry)
            rules+=( "state = floating" )
            rules+=( "sticky = on" )
            ;;
    [Gg]imp|[Ff]eh|[Pp]inentry)
            rules+=( "state = floating" )
            ;;
    [Ee]macs|[Zz]athura)
            # Needed by emacs because of issue bspwm/551
            rules+=( "state = tiled" )
            ;;
esac

case $instance in
    [Cc]apture|[Oo]rg-capture)
            rules+=( "state = floating" )
            rules+=( "sticky = on" )
            ;;
    [Ss]cratchpad)
            rules+=( "hidden = on" )
            rules+=( "sticky = on" )
            rules+=( "state = floating" )
            rules+=( "layer = normal" )
            ;;
esac

case $name in
    "Event Tester") # xev
            rules+=( "state = floating" )
            ;;
esac

echo "$rules"
