#!/usr/bin/env sh
# Run by all interactive shells.

# load aliases files
alias_dir=${HOME}/.shell/alias/
if [ -d "$alias_dir" ]; then
    for alias in "$alias_dir"/*; do
        # shellcheck source=/dev/null
        . "$alias"
    done
fi
