#!//bin/sh

# shellcheck disable=SC1090
. "${DOTFILES:-.}/shell/.shell/lib/utils.sh"

config_dir=$(bat --config-dir)

# * themes
# WAITING https://github.com/sharkdp/bat/issues/339
# git clone https://github.com/paulcpederson/solarized-sublime.git \
repository https://github.com/bricewge/solarized-sublime.git \
  "$config_dir/themes/solarized"

bat cache --build
