#!/bin/sh

set -e

# shellcheck disable=SC1090
. "${DOTFILES:-.}/shell/.shell/lib/utils.sh"

# Set default theme
if [ ! -e "$XDG_CONFIG_HOME/theme/current-theme" ]; then
    symlink ./solarized/dark.m4 "$XDG_CONFIG_HOME/theme/current-theme"
fi
