#!/bin/sh

# shellcheck disable=SC1090
. "${DOTFILES:-.}/shell/.shell/lib/utils.sh"

keyid="8929BBC573CD92063DDD979D3D36CAA0116F0F99"

# import and trust personal public key
if ! gpg --list-keys "$keyid" >/dev/null 2>&1; then
    gpg --recv-keys "$keyid"
    printf 'trust\n5\ny\n\n' | gpg --command-fd 0 --edit-key "$keyid"
    if systemctl --user --quiet is-active gpg-agents.service; then
        systemctl --user restart gpg-agent.service
    fi
fi
