#!/bin/sh
#
# Display a blured wallpaper on locked screen. It is meant to be executed
# by 'xsecurelock' by setting 'XSECURELOCK_SAVER' to this script.

ffmpeg -i "$XSECURELOCK_SAVER_WALLPAPER" \
  -filter_complex "boxblur=10:1" \
  -f image2pipe \
  - |
  mpv --no-config \
    --no-audio \
    --no-input-terminal \
    --no-stop-screensaver \
    --wid="$XSCREENSAVER_WINDOW" \
    --panscan=1.0 \
    --image-display-duration=inf \
    -
