#!/bin/sh

set -e

export DOTFILES=${DOTFILES:-$PWD}

# NOTE It doesn't download zinit's pulgins yet.

# To keep stow's hooks POSIX we use a zsh subshell to setup ZSH config
cat << EOF | zsh
set -e

# shellcheck disable=SC1090
source "$DOTFILES/shell/.shell/lib/utils.sh"

theme_template "$HOME/.zsh/theme.zsh.m4"

source "$DOTFILES/zsh/.zshenv"

repository https://github.com/zdharma/zinit.git "\$ZINIT[BIN_DIR]" v3.5
# FIXME The following return non zero
# source "\$ZINIT[BIN_DIR]/zinit.zsh"
# zinit compile
exit $?
EOF
