# -*- mode: sh -*-

# File loaded by a login zsh shell. Or in other words: only when a
# logging, with zsh as the default shell, occur.

# Load =~/.profile= in compatibility mode. By default it's not loaded
# by zsh due to incompatibilites with standart shells.
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'
